### PR TITLE
Add more events

### PR DESCRIPTION
**Pull request by i-am-the-slime**
This is in reference to #104. There might be useful functions missing to work with the payloads of the events but they can be added lazily, I suppose.

### CODE REVIEW

**Comment by i-am-the-slime** [comment]
Should I do anything more here.

**Comment by spicydonuts** [comment]
No it looks good, I just haven’t had time to merge it yet

**Comment by spicydonuts** [comment]
I will do this soon.. sorry

**Comment by i-am-the-slime** [comment]
Absolutely no problem, I'm pointing to my fork from spago very conveniently in the meantime :)

**Pull request merged**
