### PR TITLE
Add a module with types for SVG elements

### LINKED ISSUE #82: Include svg elements in React.Basic.DOM
I wanted to render an svg using purescript-react-basic, and I noticed that the svg elements seemed to be missing from React.Basic.DOM. It looks like codegen only maps over props.elements.html, but the svg elements (apart from the svg tag itself) are under props.elements.svg (according to https://www.npmjs.com/package/react-html-attributes ). I'm only learning purescript and purescript-react-basic, so I could be missing something, but it seems like it would be relatively straightforward to include all the svg elements as well. I could try to make a PR for this if it's as simple as mapping over props.elements.svg as well.

I'm also wondering if Props_svg is correct? https://github.com/lumihq/purescript-react-basic/blob/master/src/React/Basic/DOM/Generated.purs#L1542 Some of the attributes look like they shouldn't be valid for the svg tag itself, but I'm not sure (maybe the spec allows having them even if they don't do anything).

### PR DESCRIPTION
**Pull request by kryft**
Fixes #82 

@spicydonuts The codegen seems to work, but I haven't actually tested this yet in any way. (I should at least try to render an SVG. :) That will have to wait for another day, but I'd make a PR at this point to give you a chance to comment on the code.

### CODE REVIEW

**Comment by kryft** [comment]
Hmm, clearly I did something wrong here. :) I guess SharedSVGProps should at least have the  '| specific' row type polymorphism thingy that SharedProps has?

**Comment by spicydonuts** [comment]
Probably, if those props apply to all the other svg elements

**Comment by kryft** [comment]
Ok, I can build the package without warnings, and I can import it and render a simple SVG, so at least the basics seem to work. I don't know if there's a reasonable way to test this much more exhaustively than that. It's quite possible that svg-element-attributes lists an attribute that React doesn't actually support, but that's hard to verify. I did spend some time poring over MDN and the SVG2 spec, and I've done some moderately complicated React SVG rendering in the past, but I'm hardly an expert. In any case I don't see how this could break something for someone who doesn't want to render SVGs, and for someone who does, it should be a strict improvement over the current master branch. :)

@spicydonuts What do you think?

**Comment by spicydonuts** [comment]
Sorry I've been slow to follow up on this @kryft. I'll take a closer look at this now.

**Comment by kryft** [comment]
@spicydonuts No worries, I'm sure you have a lot on your plate. :)

**Comment by kryft** [comment]
@spicydonuts So would you like me to rebase this branch to fix the conflicts that merging #84 caused?

**Comment by spicydonuts** [comment]
That would be great, thank you!

**Pull request merged**
