### PR TITLE
Seems fine to switch to spago now

### PR DESCRIPTION
**Pull request by spicydonuts**
Spago made it easier to test the 0.14 changes. If this looks good I'll convert the others as well.

### CODE REVIEW

**Comment by hdgarrood** [comment]
I personally am still not sold on Spago for libraries: https://github.com/purescript/purescript/issues/3942#issuecomment-741414900

If we are going to switch then I think we should ensure that the bower.json we have checked in matches the one Spago would generate for us, and that it is exercised in CI (i.e. you can install dependencies with it and run tests with it). If we don't do this, then we might struggle to publish the package to Pursuit.

**Comment by spicydonuts** [comment]
Hmm, I see what you mean. I've been using the spago-generated bower.json in `react-basic-hooks` for a while and kind of assumed that was the "correct" approach (i.e. keep it working with the latest package set and emit a compatible bower.json for those users).

**Comment by spicydonuts** [comment]
The generated bower.json seems like the easiest way to keep supporting bower while also frequently testing with the latest package set.

**Comment by hdgarrood** [comment]
There isn't really a "correct" approach that everyone agrees on right now, unfortunately. Hopefully this will become clearer once the registry work is a bit further along. As I say though, I think checking in a generated bower.json is fine, but I think it would be better to either exercise it directly in CI (i.e. via `bower install` and then checking the library can be compiled with `pulp`), or at least to verify in CI that running the spago command to regenerate bower.json doesn't result in changes. Preferably both?

**Comment by spicydonuts** [comment]
Makes sense, I'll add those

**Pull request merged**
